# Generated by Django 3.2 on 2021-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ID',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
