# Generated by Django 3.2 on 2021-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blognum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
