# Generated by Django 3.2 on 2021-05-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0002_post_blognum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
